### PR TITLE
Fixed: inventory channel groups not showing until page refresh (#169)

### LINKED ISSUE #169: Inventory channel groups not appearing on first page load
## Current behavior

Inventory channel groups are not appearing on first page load of facility detail page:

https://jam.dev/c/562cae91-293e-4633-a5f7-0310408cdb18

### PR DESCRIPTION
**Pull request by amansinghbais**
### Related Issues

Closes #169

### Short Description and Why It's Useful

Fixed issue of inventory channel groups not showing until page refersh in facility details page.

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/facilities#contribution-guideline)

### CODE REVIEW

File: src/store/modules/facility/actions.ts [hunk 1]
```diff
@@ -183,6 +183,7 @@ const actions: ActionTree<FacilityState, RootState> = {
     const current = cachedFacilities.find((facility: any) => facility.facilityId === payload.facilityId)
     if(current?.facilityId && !payload.skipState) {
       commit(types.FACILITY_CURRENT_UPDATED, current);
+      await dispatch('fetchFacilityAdditionalInformation', payload);
```
Comment (ymaheshwari1) [inline src/store/modules/facility/actions.ts:186]: As we have found the current facility in list, its additional information is also available so we should not fetch the complete information again just to get inventory Groups.

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]

File: src/store/modules/facility/actions.ts [hunk 2]
```diff
@@ -177,11 +177,19 @@ const actions: ActionTree<FacilityState, RootState> = {
...
     // checking that if the list contains basic information for facility then not fetching the same information again
     const cachedFacilities = JSON.parse(JSON.stringify(state.facilities.list))
     const current = cachedFacilities.find((facility: any) => facility.facilityId === payload.facilityId)
     if(current?.facilityId && !payload.skipState) {
+      // As inventory channels are fetched while fetching additional facility info
+      // But here we already have additional facility info, so just getting and adding inventory groups to current.
+      const inventoryGroups = rootGetters['util/getInventoryGroups'];
+      inventoryGroups.forEach((group: any) => {
+        const isChecked = (current.facilityGroupInfo?.some((facilityGroup: any) => facilityGroup?.facilityGroupId === group.facilityGroupId))
+        group.isChecked = isChecked ? isChecked : false;
```
Comment (ymaheshwari1) [inline src/store/modules/facility/actions.ts:190]:
```suggestion
        group.isChecked = (current.facilityGroupInfo?.some((facilityGroup: any) => facilityGroup?.facilityGroupId === group.facilityGroupId))
```
There is no need to have extra check.

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]

**Review by ymaheshwari1 — APPROVED** [review]

File: src/store/modules/facility/actions.ts (hunk 2 above)
Comment (ymaheshwari1) [reply src/store/modules/facility/actions.ts:191]: This has been handled in https://github.com/hotwax/facilities/pull/182
