### PR TITLE
Fixed: loader not dismissing on telecom update and truncation in facility mappings card (#199)

### LINKED ISSUE #199: Continuous loading on the UI occurs when the user edits the phone number for the second time or thereafter.
## Current behavior
Continuous loading on the UI occurs when the user edits the phone number for the second time or thereafter.

## Expected behavior
Continuous loading should not persist on the UI, and phone number changes should be correctly updated when the user edits the phone number for the second time or thereafter.

## Steps to reproduce the issue
Open the dev-oms instance of Facilities App.
Open the facilities card and create one facility.
Add the phone number while creating the facility or edit the address after creation and add there.
Save the changes.
Again try to edit the phone number and save it.
Observe the issue.

## Environment details
- App Release version: v1.3.0
- Instance: Dev-OMS
- Environment: UAT

## Additional information
https://jam.dev/c/418c4a95-d7d5-48bf-9175-ccbd3a4ef4d9

### PR DESCRIPTION
**Pull request by amansinghbais**
### Related Issues

Closes #199

### Short Description and Why It's Useful

Fixed: 
- Loader not dismissing on mobile change 2nd or more times
- Truncation in identification value in facility mappings card.
- Added "-" as a seperator between country code and mobile number.

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/facilities#contribution-guideline)

### CODE REVIEW

File: src/views/FacilityDetails.vue [hunk 1]
```diff
@@ -354,7 +354,7 @@
                 </ion-card-title>
               </ion-card-header>
               <ion-item lines="full">
-                <ion-label>{{ translate('Identification') }}</ion-label>
+                <ion-label slot="start">{{ translate('Identification') }}</ion-label>
```
Comment (dt2patel) [inline src/views/FacilityDetails.vue:357]: why do we need to slot this label?

**Review by dt2patel — CHANGES_REQUESTED** [review]
Question about slots

File: src/views/FacilityDetails.vue (hunk 1 above)
Comment (amansinghbais) [reply src/views/FacilityDetails.vue:357]: Since we have used slot "end" in another label showing value of this identification. Ionic by default consider that as primary element of card and truncate this label. By adding slot start in the first label, it truncate the right label.

Comment (amansinghbais) [reply src/views/FacilityDetails.vue:357]: If we remove the slot end from the second label, then that label will start from the center of the card.
